import { Language } from './types';

export const INDIAN_LANGUAGES: Language[] = [
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം' },
  { code: 'or', name: 'Odia', nativeName: 'ଓଡ଼ିଆ' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ' },
  { code: 'as', name: 'Assamese', nativeName: 'অসমীয়া' },
  { code: 'ur', name: 'Urdu', nativeName: 'اردو' },
  { code: 'br', name: 'Bodo', nativeName: 'बड़ो' },
  { code: 'doi', name: 'Dogri', nativeName: 'डोगरी' },
  { code: 'ks', name: 'Kashmiri', nativeName: 'कॉशुर' },
  { code: 'kok', name: 'Konkani', nativeName: 'कोंकणी' },
  { code: 'mai', name: 'Maithili', nativeName: 'मैथिली' },
  { code: 'mni', name: 'Manipuri', nativeName: 'মণিপুরী' },
  { code: 'ne', name: 'Nepali', nativeName: 'नेपाली' },
  { code: 'sa', name: 'Sanskrit', nativeName: 'संस्कृतम्' },
  { code: 'sat', name: 'Santali', nativeName: 'संताली' },
  { code: 'sd', name: 'Sindhi', nativeName: 'सिन्धी' },
];

export const UI_TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    appName: "Prospect Assist AI",
    tagline: "Retail Lending Underwriting & Smart Conversion Platform",
    dashboard: "Dashboard Hub",
    newAssessment: "Prospect Assessment",
    leadPipeline: "Lead CRM Pipeline",
    repaymentCapacity: "Repayment Capacity",
    conversionRate: "Conversion Rate",
    actualIncome: "Actual Verified Income",
    disposableSurplus: "Monthly Disposable Surplus",
    loanProduct: "Loan Product",
    repaymentScore: "Repayment Score",
    intentScore: "Behavioral Intent",
    conversionProb: "Conversion Probability",
    redFlags: "Underwriting Risk Flags",
    positiveIndicators: "Positive Risk Indicators",
    recommendedAmount: "Recommended Max Loan",
    approvedRate: "Approved Base Rate",
    runAI: "Run Gemini AI Underwriting",
    loadProfile: "Load Simulated Profile",
    manualInput: "Manual Financial Log / Statement Paste",
    occupation: "Occupation",
    declaredIncome: "Declared Monthly Income",
    requestedLoan: "Requested Loan Type",
    requestedAmt: "Requested Amount",
    tenure: "Tenure (Years)",
    saveLead: "Save Lead to CRM",
    prospectList: "Prospect Accounts",
    conversionOver30: "Target Conversion Rate: >30%",
    savingAlert: "Lead saved successfully!",
    analyzingText: "Gemini AI is analyzing transactions, cash flows, and behavioral logs...",
    calculator: "Loan Eligibility Calculator",
    enterDetails: "Enter Financial Details",
    totalLeads: "Total Leads Analyzed",
    avgConversion: "Lead Conversion Avg",
    hotLeads: "Hot Prospects",
    underwritingTitle: "Prudent Underwriting Report",
    nationalColorsLabel: "Tricolor Theme Active",
  },
  hi: {
    appName: "प्रॉस्पेक्ट असिस्ट एआई",
    tagline: "रिटेल लेंडिंग अंडरराइटिंग और स्मार्ट कन्वर्जन प्लेटफॉर्म",
    dashboard: "डैशबोर्ड हब",
    newAssessment: "प्रत्याशी मूल्यांकन",
    leadPipeline: "लीड सीआरएम पाइपलाइन",
    repaymentCapacity: "पुनर्भुगतान क्षमता",
    conversionRate: "कन्वर्जन दर",
    actualIncome: "वास्तविक सत्यापित आय",
    disposableSurplus: "मासिक डिस्पोजेबल अधिशेष",
    loanProduct: "ऋण उत्पाद",
    repaymentScore: "पुनर्भुगतान स्कोर",
    intentScore: "व्यवहारिक इरादा",
    conversionProb: "कन्वर्जन संभावना",
    redFlags: "अंडरराइटिंग जोखिम झंडे",
    positiveIndicators: "सकारात्मक जोखिम संकेतक",
    recommendedAmount: "अनुशंसित अधिकतम ऋण",
    approvedRate: "स्वीकृत आधार दर",
    runAI: "जेमिनी एआई अंडरराइटिंग चलाएं",
    loadProfile: "सिम्युलेटेड प्रोफाइल लोड करें",
    manualInput: "मैनुअल वित्तीय लॉग / विवरण पेस्ट करें",
    occupation: "व्यवसाय",
    declaredIncome: "घोषित मासिक आय",
    requestedLoan: "अनुरोधित ऋण प्रकार",
    requestedAmt: "अनुरोधित राशि",
    tenure: "अवधि (वर्ष)",
    saveLead: "सीआरएम में लीड सहेजें",
    prospectList: "प्रत्याशी खाते",
    conversionOver30: "लक्षित कन्वर्जन दर: >30%",
    savingAlert: "लीड सफलतापूर्वक सहेजी गई!",
    analyzingText: "जेमिनी एआई लेनदेन, नकदी प्रवाह और व्यवहार लॉग का विश्लेषण कर रहा है...",
    calculator: "ऋण पात्रता कैलकुलेटर",
    enterDetails: "वित्तीय विवरण दर्ज करें",
    totalLeads: "कुल विश्लेषित लीड",
    avgConversion: "औसत लीड कन्वर्जन",
    hotLeads: "हॉट प्रॉस्पेक्ट्स",
    underwritingTitle: "विवेकपूर्ण अंडरराइटिंग रिपोर्ट",
    nationalColorsLabel: "तिरंगा थीम सक्रिय",
  },
  bn: {
    appName: "প্রস্পেক্ট অ্যাসিস্ট এআই",
    tagline: "খুচরা ঋণ আন্ডাররাইটিং এবং স্মার্ট রূপান্তর প্ল্যাটফর্ম",
    dashboard: "ড্যাশবোর্ড হাব",
    newAssessment: "প্রার্থী মূল্যায়ন",
    leadPipeline: "লিড সিআরএম পাইপলাইন",
    repaymentCapacity: "পরিশোধের ক্ষমতা",
    conversionRate: "রূপান্তর হার",
    actualIncome: "প্রকৃত যাচাইকৃত আয়",
    disposableSurplus: "মাসিক ডিসপোজেবল উদ্বৃত্ত",
    loanProduct: "ঋণ পণ্য",
    repaymentScore: "পরিশোধের স্কোর",
    intentScore: "আচরণগত উদ্দেশ্য",
    conversionProb: "রূপান্তরের সম্ভাবনা",
    redFlags: "আন্ডাররাইটিং ঝুঁকি ফ্ল্যাগ",
    positiveIndicators: "ইতিবাচক ঝুঁকি সূচক",
    recommendedAmount: "প্রস্তাবিত সর্বোচ্চ ঋণ",
    approvedRate: "অনুমোদিত বেস রেট",
    runAI: "জেমিনি এআই আন্ডাররাইটিং চালান",
    loadProfile: "সিমুলেটেড প্রোফাইল লোড করুন",
    manualInput: "ম্যানুয়াল আর্থিক লগ / বিবরণ পেস্ট করুন",
    occupation: "পেশা",
    declaredIncome: "ঘোষিত মাসিক আয়",
    requestedLoan: "অনুরোধ করা ঋণের ধরন",
    requestedAmt: "অনুরোধ করা পরিমাণ",
    tenure: "মেয়াদ (বছর)",
    saveLead: "সিআরএম-এ লিড সংরক্ষণ করুন",
    prospectList: "প্রার্থীর অ্যাকাউন্ট",
    conversionOver30: "টার্গেট রূপান্তর হার: >৩০%",
    savingAlert: "লিড সফলভাবে সংরক্ষিত হয়েছে!",
    analyzingText: "জেমিনি এআই লেনদেন, নগদ প্রবাহ এবং আচরণ লগ বিশ্লেষণ করছে...",
    calculator: "ঋণ যোগ্যতা ক্যালকুলেটর",
    enterDetails: "আর্থিক বিবরণ লিখুন",
    totalLeads: "মোট বিশ্লেষিত লিড",
    avgConversion: "গড় লিড রূপান্তর",
    hotLeads: "হট প্রস্পেক্টস",
    underwritingTitle: "যৌক্তিক আন্ডাররাইটিং রিপোর্ট",
    nationalColorsLabel: "ত্রিবর্ণ থিম সক্রিয়",
  },
  te: {
    appName: "ప్రాస్పెక్ట్ అసిస్ట్ AI",
    tagline: "రిటైల్ లెండింగ్ అండర్ రైటింగ్ & స్మార్ట్ కన్వర్షన్ ప్లాట్‌ఫాం",
    dashboard: "డ్యాష్‌బోర్డ్ హబ్",
    newAssessment: "అభ్యర్థి మూల్యాంకనం",
    leadPipeline: "లీడ్ సీఆర్ఎం పైప్‌లైన్",
    repaymentCapacity: "తిరిగి చెల్లించే సామర్థ్యం",
    conversionRate: "కన్వర్షన్ రేటు",
    actualIncome: "నిజమైన ధృవీకరించబడిన ఆదాయం",
    disposableSurplus: "నెలవారీ మిగులు",
    loanProduct: "రుణ ఉత్పత్తి",
    repaymentScore: "రీపేమెంట్ స్కోరు",
    intentScore: "ప్రవర్తనా ఉద్దేశం",
    conversionProb: "కన్వర్షన్ సంభావ్యత",
    redFlags: "అండర్ రైటింగ్ రిస్క్ ఫ్లాగ్స్",
    positiveIndicators: "సానుకూల రిస్క్ సూచికలు",
    recommendedAmount: "సిఫార్సు చేయబడిన గరిష్ట రుణం",
    approvedRate: "ఆమోదించబడిన బేస్ రేట్",
    runAI: "జెమిని AI అండర్ రైటింగ్ రన్ చేయండి",
    loadProfile: "సిమ్యులేటెడ్ ప్రొఫైల్ లోడ్ చేయండి",
    manualInput: "మాన్యువల్ ఫైనాన్షియల్ లాగ్ / స్టేట్‌మెంట్ పేస్ట్",
    occupation: "వృత్తి",
    declaredIncome: "ప్రకటించిన నెలవారీ ఆదాయం",
    requestedLoan: "అభ్యర్థించిన రుణ రకం",
    requestedAmt: "అభ్యర్థించిన మొత్తం",
    tenure: "వ్యవధి (సంవత్సరాలు)",
    saveLead: "లీడ్‌ను సేవ్ చేయండి",
    prospectList: "ప్రాస్పెక్ట్ ఖాతాలు",
    conversionOver30: "లక్ష్య కన్వర్షన్ రేటు: >30%",
    savingAlert: "లీడ్ విజయవంతంగా సేవ్ చేయబడింది!",
    analyzingText: "జెమిनी AI లావాదేవీలు మరియు ప్రవర్తనను విశ్లేషిస్తోంది...",
    calculator: "రుణ అర్హత కాలిక్యులేటర్",
    enterDetails: "ఆర్థిక వివరాలను నమోదు చేయండి",
    totalLeads: "మొత్తం విశ్లేషించబడిన లీడ్స్",
    avgConversion: "సగటు లీడ్ కన్వర్షన్",
    hotLeads: "హాట్ ప్రాస్పెక్ట్స్",
    underwritingTitle: "వివేకవంతమైన అండర్ రైటింగ్ నివేదిక",
    nationalColorsLabel: "త్రివర్ణ థీమ్ క్రియాశీలంగా ఉంది",
  },
  ta: {
    appName: "ப்ராஸ்பெக்ட் அசிஸ்ட் AI",
    tagline: "சில்லறை கடன் ஒப்புதல் மற்றும் ஸ்மார்ட் மாற்று தளம்",
    dashboard: "டாஷ்போர்டு ஹப்",
    newAssessment: "மதிப்பீடு செய்க",
    leadPipeline: "வாடிக்கையாளர் குழாய்",
    repaymentCapacity: "திருப்பிச் செலுத்தும் திறன்",
    conversionRate: "மாற்று விகிதம்",
    actualIncome: "உண்மையான சரிபார்க்கப்பட்ட வருமானம்",
    disposableSurplus: "மாதாந்திர உபரி பணம்",
    loanProduct: "கடன் தயாரிப்பு",
    repaymentScore: "திருப்பிச் செலுத்தும் மதிப்பெண்",
    intentScore: "நடத்தை சார்ந்த விருப்பம்",
    conversionProb: "மாற்று நிகழ்தகவு",
    redFlags: "ஆபத்து குறிகாட்டிகள்",
    positiveIndicators: "நேர்மறை ஆபத்து குறிகாட்டிகள்",
    recommendedAmount: "பரிந்துரைக்கப்பட்ட கடன் தொகை",
    approvedRate: "அங்கீகரிக்கப்பட்ட அடிப்படை வட்டி",
    runAI: "ஜெமினி AI பகுப்பாய்வை இயக்கு",
    loadProfile: "மாதிரி சுயவிவரத்தை ஏற்று",
    manualInput: "கைமுறையாக உள்ளீடு",
    occupation: "தொழில்",
    declaredIncome: "அறிவிக்கப்பட்ட மாத வருமானம்",
    requestedLoan: "கோரப்பட்ட கடன் வகை",
    requestedAmt: "கோரப்பட்ட தொகை",
    tenure: "கால அளவு (ஆண்டுகள்)",
    saveLead: "விவரத்தை சேமி",
    prospectList: "வாடிக்கையாளர் கணக்குகள்",
    conversionOver30: "இலக்கு மாற்று விகிதம்: >30%",
    savingAlert: "வெற்றிகரமாக சேமிக்கப்பட்டது!",
    analyzingText: "ஜெமினி AI பரிவர்த்தனைகளை ஆய்வு செய்கிறது...",
    calculator: "கடன் தகுதி கால்குலேட்டர்",
    enterDetails: "நிதி விவரங்களை உள்ளிடவும்",
    totalLeads: "மொத்த பகுப்பாய்வுகள்",
    avgConversion: "சராசரி மாற்று விகிதம்",
    hotLeads: "முக்கிய வாடிக்கையாளர்கள்",
    underwritingTitle: "முறையான கடன் ஒப்புதல் அறிக்கை",
    nationalColorsLabel: "தேசிய மூவண்ண கருப்பொருள்",
  },
  mr: {
    appName: "प्रॉस्पेक्ट असिस्ट AI",
    tagline: "रिटेल लेंडिंग अंडररायटिंग आणि स्मार्ट कन्व्हर्जन प्लॅटफॉर्म",
    dashboard: "डॅशबोर्ड हब",
    newAssessment: "उमेदवार मूल्यमापन",
    leadPipeline: "लीड सीआरएम पाइपलाइन",
    repaymentCapacity: "परतावा क्षमता",
    conversionRate: "कन्व्हर्जन दर",
    actualIncome: "वास्तविक सत्यापित उत्पन्न",
    disposableSurplus: "मासिक डिस्पोजेबल अतिरिक्त",
    loanProduct: "कर्ज उत्पादन",
    repaymentScore: "परतावा स्कोअर",
    intentScore: "वर्तणूक हेतू",
    conversionProb: "कन्व्हर्जन शक्यता",
    redFlags: "अंडररायटिंग जोखीम चिन्हे",
    positiveIndicators: "सकारात्मक जोखीम निर्देशक",
    recommendedAmount: "शिफारस केलेले कमाल कर्ज",
    approvedRate: "मंजूर बेस दर",
    runAI: "जेमिनी एआय अंडररायटिंग चालवा",
    loadProfile: "सिम्युलेटेड प्रोफाईल लोड करा",
    manualInput: "मॅन्युअल वित्तीय लॉग / विवरण पेस्ट करा",
    occupation: "व्यवसाय",
    declaredIncome: "घोषित मासिक उत्पन्न",
    requestedLoan: "विनंती केलेला कर्जाचा प्रकार",
    requestedAmt: "विनंती केलेली रक्कम",
    tenure: "मुदत (वर्षे)",
    saveLead: "सीआरएम मध्ये लीड जतन करा",
    prospectList: "संभाव्य ग्राहक",
    conversionOver30: "लक्ष्य कन्व्हर्जन दर: >३०%",
    savingAlert: "लीड यशस्वीरित्या जतन केली!",
    analyzingText: "जेमिनी एआय विश्लेषण करत आहे...",
    calculator: "कर्ज पात्रता कॅल्क्युलेटर",
    enterDetails: "वित्तीय तपशील प्रविष्ट करा",
    totalLeads: "एकूण विश्लेषित लीड्स",
    avgConversion: "सरासरी लीड कन्व्हर्जन",
    hotLeads: "हॉट प्रॉस्पेक्ट्स",
    underwritingTitle: "अंडररायटिंग अहवाल",
    nationalColorsLabel: "तिरंगा थीम सक्रिय",
  },
  gu: {
    appName: "પ્રોસ્પેક્ટ આસિસ્ટ AI",
    tagline: "રિટેલ ધિરાણ અન્ડરરાઈટિંગ અને સ્માર્ટ કન્વર્ઝન પ્લેટફોર્મ",
    dashboard: "ડેશબોર્ડ હબ",
    newAssessment: "ઉમેદવાર મૂલ્યાંકન",
    leadPipeline: "લીડ સીઆરએમ પાઇપલાઇન",
    repaymentCapacity: "ચુકવણી ક્ષમતા",
    conversionRate: "કન્વર્ઝન દર",
    actualIncome: "વાસ્તવિક ચકાસાયેલ આવક",
    disposableSurplus: "માસિક નિકાલજોગ સરપ્લસ",
    loanProduct: "લોન ઉત્પાદન",
    repaymentScore: "ચુકવણી સ્કોર",
    intentScore: "વર્તણૂકીય હેતુ",
    conversionProb: "કન્વર્ઝન સંભાવના",
    redFlags: "જોખમ ચિહ્નો",
    positiveIndicators: "હકારાત્મક જોખમ સંકેતો",
    recommendedAmount: "ભલામણ કરેલ મહત્તમ લોન",
    approvedRate: "મંજૂર બેઝ રેટ",
    runAI: "જેમિની AI અન્ડરરાઇટિંગ ચલાવો",
    loadProfile: "પ્રોફાઇલ લોડ કરો",
    manualInput: "નાણાકીય વિગતો પેસ્ટ કરો",
    occupation: "વ્યવસાય",
    declaredIncome: "જાહેર માસિક આવક",
    requestedLoan: "લોન પ્રકાર",
    requestedAmt: "વિનંતી કરેલ રકમ",
    tenure: "સમયગાળો (વર્ષો)",
    saveLead: "લીડ સાચવો",
    prospectList: "ગ્રાહક યાદી",
    conversionOver30: "ટાર્ગેટ કન્વર્ઝન દર: >30%",
    savingAlert: "લીડ સફળતાપૂર્વક સાચવવામાં આવી!",
    analyzingText: "જેમિની AI વિશ્લેષણ કરી રહ્યું છે...",
    calculator: "પાત્રતા કેલ્ક્યુલેટર",
    enterDetails: "નાણાકીય વિગતો દાખલ કરો",
    totalLeads: "કુલ લોન લીડ્સ",
    avgConversion: "સરેરાશ કન્વર્ઝન",
    hotLeads: "હૉટ પ્રોસ્પેક્ટ્સ",
    underwritingTitle: "વિવેકપૂર્ણ અન્ડરરાઇટિંગ રિપોર્ટ",
    nationalColorsLabel: "ત્રિરંગો થીમ સક્રિય",
  },
  kn: {
    appName: "ಪ್ರಾಸ್ಪೆಕ್ಟ್ ಅಸಿಸ್ಟ್ AI",
    tagline: "ಚಿಲ್ಲರೆ ಸಾಲ ಅಂಡರ್ರೈಟಿಂಗ್ ಮತ್ತು ಸ್ಮಾರ್ಟ್ ಪರಿವರ್ತನೆ ವೇದಿಕೆ",
    dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ಹಬ್",
    newAssessment: "ಅಭ್ಯರ್ಥಿ ಮೌಲ್ಯಮಾಪನ",
    leadPipeline: "ಲೀಡ್ ಸಿಆರ್‌ಎಂ ಪೈಪ್‌ಲೈನ್",
    repaymentCapacity: "ಮರುಪಾವತಿ ಸಾಮರ್ಥ್ಯ",
    conversionRate: "ಪರಿವರ್ತನೆ ದರ",
    actualIncome: "ನೈಜ ಪರಿಶೀಲಿಸಿದ ಆದಾಯ",
    disposableSurplus: "ಮಾಸಿಕ ಉಳಿಕೆ",
    loanProduct: "ಸಾಲದ ಉತ್ಪನ್ನ",
    repaymentScore: "ಮರುಪಾವತಿ ಸ್ಕೋರ್",
    intentScore: "ವರ್ತನೆಯ ಉದ್ದೇಶ",
    conversionProb: "ಪರಿವರ್ತನೆಯ ಸಂಭವನೀಯತೆ",
    redFlags: "ಅಪಾಯದ ಗುರುತುಗಳು",
    positiveIndicators: "ಸಕಾರಾತ್ಮಕ ಅಪಾಯದ ಸೂಚಕಗಳು",
    recommendedAmount: "ಶಿಫಾರಸು ಮಾಡಿದ ಗರಿಷ್ಠ ಸಾಲ",
    approvedRate: "ಮಂಜೂರಾದ ಮೂಲ ದರ",
    runAI: "ಜೆಮಿನಿ AI ವಿಶ್ಲೇಷಣೆ ರನ್ ಮಾಡಿ",
    loadProfile: "ಪ್ರೊಫೈಲ್ ಲೋಡ್ ಮಾಡಿ",
    manualInput: "ಹಣಕಾಸು ವಿವರಗಳನ್ನು ಪೇಸ್ಟ್ ಮಾಡಿ",
    occupation: "ಉದ್ಯೋಗ",
    declaredIncome: "ಘೋಷಿತ ಮಾಸಿಕ ಆದಾಯ",
    requestedLoan: "ಸಾಲದ ಪ್ರಕಾರ",
    requestedAmt: "ಕೋರಿದ ಮೊತ್ತ",
    tenure: "ಅವಧಿ (ವರ್ಷಗಳು)",
    saveLead: "ಲೀಡ್ ಉಳಿಸಿ",
    prospectList: "ಗ್ರಾಹಕರ ಪಟ್ಟಿ",
    conversionOver30: "ಗುರಿ ಪರಿವರ್ತನೆ ದರ: >30%",
    savingAlert: "ಯಶಸ್ವಿಯಾಗಿ ಉಳಿಸಲಾಗಿದೆ!",
    analyzingText: "ಜೆಮಿನಿ AI ವಿಶ್ಲೇಷಿಸುತ್ತಿದೆ...",
    calculator: "ಸಾಲ ಅರ್ಹತೆ ಕ್ಯಾಲ್ಕುಲೇಟರ್",
    enterDetails: "ವಿವರಗಳನ್ನು ನಮೂದಿಸಿ",
    totalLeads: "ಒಟ್ಟು ವಿಶ್ಲೇಷಿಸಿದ ಲೀಡ್ಸ್",
    avgConversion: "ಸರಾಸರಿ ಪರಿವರ್ತನೆ",
    hotLeads: "ಹಾಟ್ ಪ್ರಾಸ್ಪೆಕ್ಟ್ಸ್",
    underwritingTitle: "ವಿವೇಚನಾಶೀಲ ಅಂಡರ್ರೈಟಿಂಗ್ ವರದಿ",
    nationalColorsLabel: "ತ್ರಿವರ್ಣ ಥೀಮ್ ಸಕ್ರಿಯ",
  }
};

// Fallback logic to get translations helper
export function getTranslation(langCode: string, key: string): string {
  const translations = UI_TRANSLATIONS[langCode] || UI_TRANSLATIONS['en'];
  return translations[key] || UI_TRANSLATIONS['en'][key] || key;
}
